In [29]:
import os
import numpy as np
import pandas as pd
import sklearn.utils
import utils
import IPython.display as ipd

# Get track ids

In [31]:
artists = pd.read_csv('../MSD_FMA_artists.csv')['name'].values

In [37]:
tracks = utils.load('../../../tracks.csv')

In [54]:
ipd.display(tracks['artist'].head(100))

,active_year_begin,active_year_end,associated_labels,bio,comments,date_created,favorites,id,latitude,location,longitude,members,name,related_projects,tags,website,wikipedia_page
track_id,,,,,,,,,,,,,,,,,
2,2006-01-01,NaT,NaN,"<p>A Way Of Life, A Collective of Hip-Hop from...",0,2008-11-26 01:42:32,9,1,40.058324,New Jersey,-74.405661,"Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...",AWOL,The list of past projects is 2 long but every1...,[awol],http://www.AzillionRecords.blogspot.com,NaN
3,2006-01-01,NaT,NaN,"<p>A Way Of Life, A Collective of Hip-Hop from...",0,2008-11-26 01:42:32,9,1,40.058324,New Jersey,-74.405661,"Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...",AWOL,The list of past projects is 2 long but every1...,[awol],http://www.AzillionRecords.blogspot.com,NaN
5,2006-01-01,NaT,NaN,"<p>A Way Of Life, A Collective of Hip-Hop from...",0,2008-11-26 01:42:32,9,1,40.058324,New Jersey,-74.405661,"Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...",AWOL,The list of past projects is 2 long but every1...,[awol],http://www.AzillionRecords.blogspot.com,NaN
10,NaT,NaT,"Mexican Summer, Richie Records, Woodsist, Skul...","<p><span style=""font-family:Verdana, Geneva, A...",3,2008-11-26 01:42:55,74,6,NaN,NaN,NaN,"Kurt Vile, the Violators",Kurt Vile,NaN,"[philly, kurt vile]",http://kurtvile.com,NaN
20,1990-01-01,2011-01-01,NaN,<p>Songs written by: Nicky Cook</p>\n<p>VOCALS...,2,2008-11-26 01:42:52,10,4,51.895927,Colchester England,0.891874,Nicky Cook\n,Nicky Cook,NaN,"[instrumentals, experimental pop, post punk, e...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,NaT,NaT,NaN,<p>Brattleboro VT via Athens GA via Chicago IL...,7,2008-11-26 01:53:25,27,80,NaN,NaN,NaN,NaN,Bird Names,NaN,"[athens ga, bird names, athens, vermont, chica...",http://northern-spy.com/artists/bird-names/,NaN
252,NaT,NaT,NaN,<p>Brattleboro VT via Athens GA via Chicago IL...,7,2008-11-26 01:53:25,27,80,NaN,NaN,NaN,NaN,Bird Names,NaN,"[athens ga, bird names, athens, vermont, chica...",http://northern-spy.com/artists/bird-names/,NaN
253,NaT,NaT,NaN,<p>Brattleboro VT via Athens GA via Chicago IL...,7,2008-11-26 01:53:25,27,80,NaN,NaN,NaN,NaN,Bird Names,NaN,"[athens ga, bird names, athens, vermont, chica...",http://northern-spy.com/artists/bird-names/,NaN
254,NaT,NaT,NaN,<p>Brattleboro VT via Athens GA via Chicago IL...,7,2008-11-26 01:53:25,27,80,NaN,NaN,NaN,NaN,Bird Names,NaN,"[athens ga, bird names, athens, vermont, chica...",http://northern-spy.com/artists/bird-names/,NaN
255,NaT,NaT,NaN,<p>Brattleboro VT via Athens GA via Chicago IL...,7,2008-11-26 01:53:25,27,80,NaN,NaN,NaN,NaN,Bird Names,NaN,"[athens ga, bird names, athens, vermont, chica...",http://northern-spy.com/artists/bird-names/,NaN

In [47]:
filtered_track_ids = tracks[tracks[('artist', 'name')].str.lower().isin(artists)].index
filtered_track_ids

Index([    10,    156,    157,    158,    159,    160,    161,    162,    163,
          164,
       ...
       154420, 154421, 154422, 154774, 154835, 154836, 154837, 155000, 155031,
       155056],
      dtype='int64', name='track_id', length=7199)

In [72]:
tracks.loc[tracks[('track', 'title')] == 'BangBang', ('track')]

,bit_rate,comments,composer,date_created,date_recorded,duration,favorites,genre_top,genres,genres_all,information,interest,language_code,license,listens,lyricist,number,publisher,tags,title
track_id,,,,,,,,,,,,,,,,,,,,
80295,192000,0,NaN,2013-03-14 01:02:30,NaT,142,0,Hip-Hop,[21],[21],NaN,1319,NaN,Attribution-Noncommercial-Share Alike 3.0 Unit...,715,NaN,5,NaN,[],BangBang

In [ ]:
tracks[('track', 'title')]

# Get audios

In [ ]:
fma = utils.FreeMusicArchive(os.environ.get('FMA_KEY'))

In [51]:
track_file = fma.get_track(10, 'track_file')
fma.download_track(track_file, path='track.mp3')

TypeError: can only concatenate str (not "NoneType") to str