In [2]:
import os
import numpy as np
import pandas as pd
import sklearn.utils
import utils
import IPython.display as ipd

# Get track subset

In [3]:
tracks = utils.load('../../../tracks.csv')

In [4]:
small = tracks[tracks['set', 'subset'] <= 'small']
small.head()

            album                                                           \
         comments        date_created date_released engineer favorites  id
track_id
2               0 2008-11-26 01:44:45    2009-01-05      NaN         4   1
5               0 2008-11-26 01:44:45    2009-01-05      NaN         4   1
10              0 2008-11-26 01:45:08    2008-02-06      NaN         4   6
140             1 2008-11-26 01:49:59    2007-05-22      NaN         1  61
141             0 2008-11-26 01:49:57    2009-01-16      NaN         1  60

                                                                     \
                                                information listens
track_id
2                                                   <p></p>    6073
5                                                   <p></p>    6073
10                                                      NaN   47632
140       <p>Alec K. Redfearn &amp; The Eyesores: Ellen ...    1300
141       <p>A full ensamble of strings, drums, electron...    1304

                                               ...       track           \
                                producer tags  ... information interest
track_id                                       ...
2                                    NaN   []  ...         NaN     4656
5                                    NaN   []  ...         NaN     1933
10                                   NaN   []  ...         NaN    54881
140       Alec K. Refearn, Rob Pemberton   []  ...         NaN     1593
141                                  NaN   []  ...         NaN      839

                                                                           \
         language_code                                            license
track_id
2                   en  Attribution-NonCommercial-ShareAlike 3.0 Inter...
5                   en  Attribution-NonCommercial-ShareAlike 3.0 Inter...
10                  en  Attribution-NonCommercial-NoDerivatives (aka M...
140                 en  Attribution-Noncommercial-No Derivative Works ...
141                 en  Attribution-Noncommercial-No Derivative Works ...


         listens lyricist number publisher tags               title
track_id
2           1293      NaN      3       NaN   []                Food
5           1151      NaN      6       NaN   []          This World
10         50135      NaN      1       NaN   []             Freeway
140         1299      NaN      2       NaN   []  Queen Of The Wires
141          725      NaN      4       NaN   []                Ohio

[5 rows x 52 columns]

In [6]:
result = small[[('track', 'title'), ('track', 'genre_top'), ('artist', 'name')]]
result.columns = ['track title', 'genre', 'artist name']
result.head()

                 track title    genre                      artist name
track_id
2                       Food  Hip-Hop                             AWOL
5                 This World  Hip-Hop                             AWOL
10                   Freeway      Pop                        Kurt Vile
140       Queen Of The Wires     Folk  Alec K. Redfearn & the Eyesores
141                     Ohio     Folk  Alec K. Redfearn & the Eyesores

In [7]:
result.to_csv('metadata.csv', index=True)

In [ ]:
# pd.read_table('checksums', sep=r'\s+', header=None, names=['checksum', 'filename'])

                                       checksum        filename
0      6976e70271234351250ada3fc49c5afd69ba9864  000/000002.mp3
1      6aa65ac1b6e8c88b0c1117e9c29034dc70d41f3a  000/000003.mp3
2      d25363d1167965f376a0e837fa5faa662598cfe5  000/000005.mp3
3      0efc06eab57f36065d7ccff153db8fa2d16df28f  000/000010.mp3
4      2aa74827b1dedb243fe6d3b9e1290b0913e8cb5c  000/000134.mp3
...                                         ...             ...
24995  2691c694eabf0b87f0a005599e7364224fa98f47  155/155297.mp3
24996  9d579e2c379796bd41071f3ba6feff425c3caeea  155/155298.mp3
24997  5694f03263ec7ae6b6b74d3ed00c996fe3e2ab6a  155/155306.mp3
24998  ce0aa9e470eadca323e971d0dd80c77f6b7189b7  155/155307.mp3
24999  e67d54db3cc06be9b9deace3903fc0658cf20f51  155/155314.mp3

[25000 rows x 2 columns]